### ISSUE TITLE
USB make device panic on OnePlus Nord 2 5G OSS kernel

### ISSUE THREAD

**Issue by Mashopy** [OnePlusOSS/android_kernel_oneplus_mt6893#2]
Hello, I noticied that **USB were making kernel panic** with the current source code released by OnePlus, it would be really usefull if that's fixed soon.

Also, I request for **MediaTek kernel modules** and **cust.dtsi and dts for oplus6893_20817 oplus6893_20615 oplus6893_20827 and oplus6893_20831** to be generated and added at their respective directories (Need to be generated from Nord 2 5G BSP since MediaTek removed to possibility to do so on kernel itself since Android 11)

@OnePlusTomCheng

**Comment by techyminati** [comment]
Yeah @OnePlusOSSAdmin @OnePlusTomCheng , Please push Mtk kernel modules ( vendor/mediatek/kernel_modules ) They're part of kernel code too & are under GPL ( PS: realme oss released them too ) . Also push cust.dtsi for oplus6893_20817 as we can't generate them from kernel tree itself as @TheMalachite Elaborated. Thanks !

**Comment by 8vasa8** [comment]
@OnePlusOSSAdmin, @OnePlusTomCheng
Please help us with this.

**Comment by akshay7407** [comment]
@OnePlusOSSAdmin @OnePlusTomcheng please help us with this

**Comment by heraldjose10** [comment]
@OnePlusOSSAdmin Please release the Mtk kernel modules

**Comment by 100rbhthakur** [comment]
Please check. @OnePlusOSSAdmin @oneplusTomCheng

**Comment by HyperX2mate** [comment]
Help us with this

**Comment by risabhsharma71** [comment]
@OnePlusOSSAdmin please look into it.

**Comment by ghost** [comment]
Please check. @OnePlusOSSAdmin

**Comment by Yatinmanjunath8** [comment]
Please look into this @OnePlusOSSAdmin

**Comment by mp3399** [comment]
> Hello, I noticied that **USB were making kernel panic** with the current source code released by OnePlus, it would be really usefull if that's fixed soon.
> 
> Also, I request for **MediaTek kernel modules** and **cust.dtsi for oplus6893_20817** to be generated and added at **arch/am64/boot/dts/oplus6893_20817** (Need to be generated from Nord 2 5G BSP since MediaTek removed to possibility to do so on kernel itself since Android 11)
> 
> @OnePlusTomCheng

Please Fix This, Community is oneplus core audience, so don't ignore us

**Comment by Mashopy** [comment]
@oneplustomcheng It's already been 1 full month and not even an answer

**Comment by Voldemort7273** [comment]
@OnePlusTomCheng why ignoring us? Being a reputated brand we do expect atleast a reply from you ...

**Comment by techyminati** [comment]
@OnePlusOSSAdmin @OnePlusTomCheng , Sorry to say but **realme-kernel-opensource** does better job than you guys, atleast they listen to users and fix sources if they're broken. While you guys dont.

**Comment by sidxF** [comment]
Please help us with this @OnePlusOSSAdmin , it's been more than a month, how can y'all be so careless , fix the sources please

**Comment by 8vasa8** [comment]
Hello @OnePlusOSSAdmin and @OnePlusTomCheng
This is my first OP device that I bought and main reason was that kernel source was release. But I can see now how you don't care about your customers. I still hope you will help us but if not this will be my last OP device ever...

**Comment by InfnteLights** [comment]
bump!
@OnePlusOSSAdmin

**Comment by ayushrhll** [comment]
@OnePlusOSSAdmin Please update the kernel sources for this device, it's been a month, why are you guys not updating the kernel source?

**Comment by sidxF** [comment]
When are you gonna fix the kernel please fix it, it's been two months

**Comment by kitsune31** [comment]
@OnePlusOSSAdmin @OnePlusTomCheng Please update the kernel source for this device. It's been 2 months company is ignoring this issue. I hope OnePlus stays OnePlus.

**Comment by karthikeyann** [comment]
Requesting again @OnePlusOSSAdmin  @OnePlusTomCheng @OnePlusOSS

**Comment by Suru-web** [comment]
We need custom rom support soon, please fix all the issues @OnePlusOSSAdmin

**Comment by 100rbhthakur** [comment]
@OnePlusOSSAdmin please listen to us are we mad requesting aur you peoples are not even replying a word.
Shame on OnePlus.

**Comment by eastw1ng** [comment]
How is it possible that OnePlus fails at holding up their standards. This problem should have been fixed long ago and the proper standard ROM should have been available on their website since the launch.

If they fail to support their phone like they usually do, it will be the end of their brand for the majority of the users. I truly hope they will fix these issues soon and bring the state of the Nord 2 to the standard we were used to!

**Comment by aizen9876** [comment]
@OnePlusOSSAdmin  listen to us, other brand's devices launched even after nord 2 are all getting good development and you can't even release it so the devs could move furthur now.

**Comment by Suru-web** [comment]
@OnePlusOSSAdmin guys please listen to us..

**Comment by Suru-web** [comment]
@OnePlusOSSAdmin guys we want good developement support.. first of all you are using color os code base now.. then u are not even fixing the kernal issue.. do something, we want custom rom support

**Comment by aizen9876** [comment]
@OnePlusOSSAdmin  please fix the issue by taking it some time , that would be really helpful for us.

**Comment by techyminati** [comment]
@OnePlusOSSAdmin you guys are rarted, Not fixing kernel sources even after tonns of spams, @realme-kernel-opensource & @oppo-source is much better than you guys, atleast oppo-oss and realme-oss teams listen to custom developer feedback and respond to it unlike oneplus. Oneplus is now what it was not mean to be, non developer friendly OEM, Shame!

**Comment by sarthakroy2002** [comment]
> @OnePlusOSSAdmin you guys are rarted, Not fixing kernel sources even after tonns of spams, @realme-kernel-opensource & @oppo-source is much better than you guys, atleast oppo-oss and realme-oss teams listen to custom developer feedback and respond to it unlike oneplus. Oneplus is now what it was not mean to be, non developer friendly OEM, Shame!

Exactly @realme-kernel-opensource published my secondary device kernel source. It was perfect without any issues. Also gave kernel modules which itself is a plus point. Oneplus lost its legacy of OSS support to developers. Shameful @OnePlusOSSAdmin .

**Comment by aizen9876** [comment]
Tbh i was happy to choose one plus device over mi 11x or realme, they both have tons of roms Now and this doesn't even have one, such a Worst experience, i must say. 
Be Friendly to developers like mi and Learn from it  @OnePlusOSSAdmin

**Comment by sidxF** [comment]
Please fix this kernel , we really need a custom rom , where's the OnePlus that was once developer friendly, you guys don't give a shit about customers anymore even realme devices have custom roms now and we don't and that's just bullshit, I hope you still care about your brand value and reputation, save it before it's long gone

**Comment by kitsune31** [comment]
Shame Shame @OnePlusOSSAdmin @OneplusOSS @OnePlusTomCheng

**Comment by karthikeyann** [comment]
Taking this thread to twitter would get more eyes.

**Comment by sidxF** [comment]
> Taking this thread to twitter would get more eyes.

True that we should take this to Twitter, pretty sure we'll get atleast some form of response there

**Comment by 100rbhthakur** [comment]
> Taking this thread to twitter would get more eyes.

Yes I think so...

**Comment by aizen9876** [comment]
Guys, please Mention them here and Please tweet them as well, tweeting them would help us fix it faster rather than Posting it here.

**Comment by wkcs** [comment]
> Hello, I noticied that **USB were making kernel panic** with the current source code released by OnePlus, it would be really usefull if that's fixed soon.

Can you help me explain in detail your recurrence steps?

Thanks

**Comment by Mashopy** [comment]
> > Hello, I noticied that **USB were making kernel panic** with the current source code released by OnePlus, it would be really usefull if that's fixed soon.
> 
> Can you help me explain in detail your recurrence steps?
> 
> Thanks

Just flashing the kernel builded from this repo and try to connect the device to PC with an USB cable make it panic, tried from recovery.

It should also happen by just connecting the device to a charger since dmesg reported kernel panic with power delivery (PD) drivers and MediaTek typec one

**Comment by Mashopy** [comment]
Also, the missing stuff I asked didn't get added in the latest commit from today

**Comment by wkcs** [comment]
> > > Hello, I noticied that **USB were making kernel panic** with the current source code released by OnePlus, it would be really usefull if that's fixed soon.
> > 
> > Can you help me explain in detail your recurrence steps?
> > 
> > Thanks
> 
> Just flashing the kernel builded from this repo and try to connect the device to PC with an USB cable make it panic, tried from recovery.
> 
> It should also happen by just connecting the device to a charger since dmesg reported kernel panic with power delivery (PD) drivers and MediaTek typec one

Can you help provide a dmesg log.

Thank you so much

**Comment by Mashopy** [comment]
> > > > Hello, I noticied that **USB were making kernel panic** with the current source code released by OnePlus, it would be really usefull if that's fixed soon.
> > > 
> > > 
> > > Can you help me explain in detail your recurrence steps?
> > > Thanks
> > 
> > 
> > Just flashing the kernel builded from this repo and try to connect the device to PC with an USB cable make it panic, tried from recovery.
> > It should also happen by just connecting the device to a charger since dmesg reported kernel panic with power delivery (PD) drivers and MediaTek typec one
> 
> Can you help provide a dmesg log.
> 
> Thank you so much

[dmesg.log](https://github.com/OnePlusOSS/android_kernel_oneplus_mt6893/files/7719211/dmesg.log)
It's from a TWRP build when I was building kernel from this repo, USB didn't panic with stock kernel however

**Comment by Mashopy** [comment]
> > > > > Hello, I noticied that **USB were making kernel panic** with the current source code released by OnePlus, it would be really usefull if that's fixed soon.
> > > > 
> > > > 
> > > > Can you help me explain in detail your recurrence steps?
> > > > Thanks
> > > 
> > > 
> > > Just flashing the kernel builded from this repo and try to connect the device to PC with an USB cable make it panic, tried from recovery.
> > > It should also happen by just connecting the device to a charger since dmesg reported kernel panic with power delivery (PD) drivers and MediaTek typec one
> > 
> > 
> > Can you help provide a dmesg log.
> > Thank you so much
> 
> [dmesg.log](https://github.com/OnePlusOSS/android_kernel_oneplus_mt6893/files/7719211/dmesg.log) It's from a TWRP build when I was building kernel from this repo, USB didn't panic with stock kernel however

[console-ramoops.log](https://github.com/OnePlusOSS/android_kernel_oneplus_mt6893/files/7719281/console-ramoops.log)
Here the console-ramoops as well

**Comment by techyminati** [comment]
@wkcs you are from Oneplus Opensource Team? If yes please push **MediaTek kernel modules** & **cust.dtsi** .

**Comment by karthikeyann** [comment]
Submitted a bug https://forums.oneplus.com/threads/open-source-mediatek-kernel-modules-cust-dtsi.1529077/

**Comment by NotKit** [comment]
@TheMalachite I had to look into this for Ubuntu Touch port. The direct cause for kernel panic is uninitialized charger manager in mtk_charger driver. When checking further, battery controller did not get detected.

It seems OnePlus did `s/vooc/wrap/g` during preparing kernel source release for Nord 2. Compare https://github.com/OnePlusOSS/android_kernel_oneplus_mt6893/tree/oneplus/MT6893_R_11.0/drivers/power/oplus/wrap_ic with say https://github.com/realme-kernel-opensource/realmeGT_AndroidR-kernel-source/tree/master/drivers/power/oplus/vooc_ic. One side-effect is that it also breaks DT parsing, so it does not work with stock dtb/dtbo.

Did this as a workaround for now so it can work with both prebuilt and source-compiled DT: https://gitlab.com/ubports/community-ports/android11/oneplus-nord-2/kernel-oneplus-mt6893/-/commit/d14fa08727ed5f8f46c2f315825f04f7713089a9
